image: hashicorp/terraform:1.9.8

stages:
  - plan
  - apply

variables:
  TF_ROOT: "vault-pysmoke"

# ---------- PLAN ----------

plan:
  stage: plan
  script:
    - cd "$TF_ROOT"
    - terraform init -input=false
    - terraform plan \
        -input=false \
        -out=tfplan \
        -var="vault_addr=${VAULT_ADDR}" \
        -var="vault_namespace=${VAULT_NAMESPACE}"
  artifacts:
    paths:
      - $TF_ROOT/tfplan
  only:
    - merge_requests
    - main
    - master

# ---------- APPLY (manual) ----------

apply:
  stage: apply
  needs:
    - job: plan
      artifacts: true
  script:
    - cd "$TF_ROOT"
    - terraform init -input=false
    - terraform apply -input=false tfplan
  when: manual
  only:
    - main
    - master
